
import type { Metadata } from "next";
import classes from './layout.module.css';
import Footer from "../components/ui/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
          <div className={classes.pageContent}>
        {children}
      </div>
      <Footer></Footer>
    </>
  );
}
