import type { Metadata } from "next";
import { Tilt_Warp, Montserrat } from "next/font/google";
import { ViewTransitions } from 'next-view-transitions';

import "../globals.css";

/*
const tiltWarp = Tilt_Warp({
  variable: "--font-tilt-warp",
});
*/

const tiltWarp = Tilt_Warp({
  subsets: ['latin'], // ✅ specify at least one subset
  preload: true       // ✅ optional, but if true, subsets are required
});

const montserratFont = Montserrat({
  subsets: ['latin'], // ✅ specify at least one subset
  preload: true       // ✅ optional, but if true, subsets are required
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    console.log('we are in the auth layout file');
  return (
    <ViewTransitions>
      {children}
    </ViewTransitions>
  );
}
