import type { Metadata } from "next";
import { Tilt_Warp, Montserrat } from "next/font/google";
import Modal from "./components/modal/Modal";
import { ModalContextProvider } from "@/store/ModalContext";
import "./globals.css";

const tiltWarp = Tilt_Warp({
  variable: '--font-tilt-warp',
  subsets: ['latin'], // ✅ specify at least one subset
  preload: true       // ✅ optional, but if true, subsets are required
});

const montserratFont = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'], // ✅ specify at least one subset
  preload: true       // ✅ optional, but if true, subsets are required
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 return (
      <html lang="en">
        <body className={`${montserratFont.className} ${tiltWarp.className}`}>
          <ModalContextProvider>
            <Modal></Modal>
            <div id="modal"></div>
            <div className="page">
                {children}
            </div>
          </ModalContextProvider>
        </body>
      </html>
  );
}
